/* This file is auto-generated from "geldkarte_blog.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef GELDKARTE_BLOG_H
#define GELDKARTE_BLOG_H

/** @page P_LC_GELDKARTE_BLOG_PUBLIC LC_GeldKarte_BLog (public)
This page describes the properties of LC_GELDKARTE_BLOG
@anchor LC_GELDKARTE_BLOG_Status
<h3>Status</h3>
<p>
</p>
<p>
Set this property with @ref LC_GeldKarte_BLog_SetStatus, 
get it with @ref LC_GeldKarte_BLog_GetStatus
</p>

@anchor LC_GELDKARTE_BLOG_BSeq
<h3>BSeq</h3>
<p>
</p>
<p>
Set this property with @ref LC_GeldKarte_BLog_SetBSeq, 
get it with @ref LC_GeldKarte_BLog_GetBSeq
</p>

@anchor LC_GELDKARTE_BLOG_LSeq
<h3>LSeq</h3>
<p>
</p>
<p>
Set this property with @ref LC_GeldKarte_BLog_SetLSeq, 
get it with @ref LC_GeldKarte_BLog_GetLSeq
</p>

@anchor LC_GELDKARTE_BLOG_Value
<h3>Value</h3>
<p>
</p>
<p>
Set this property with @ref LC_GeldKarte_BLog_SetValue, 
get it with @ref LC_GeldKarte_BLog_GetValue
</p>

@anchor LC_GELDKARTE_BLOG_MerchantId
<h3>MerchantId</h3>
<p>
</p>
<p>
Set this property with @ref LC_GeldKarte_BLog_SetMerchantId, 
get it with @ref LC_GeldKarte_BLog_GetMerchantId
</p>

@anchor LC_GELDKARTE_BLOG_HSeq
<h3>HSeq</h3>
<p>
</p>
<p>
Set this property with @ref LC_GeldKarte_BLog_SetHSeq, 
get it with @ref LC_GeldKarte_BLog_GetHSeq
</p>

@anchor LC_GELDKARTE_BLOG_SSeq
<h3>SSeq</h3>
<p>
</p>
<p>
Set this property with @ref LC_GeldKarte_BLog_SetSSeq, 
get it with @ref LC_GeldKarte_BLog_GetSSeq
</p>

@anchor LC_GELDKARTE_BLOG_Loaded
<h3>Loaded</h3>
<p>
</p>
<p>
Set this property with @ref LC_GeldKarte_BLog_SetLoaded, 
get it with @ref LC_GeldKarte_BLog_GetLoaded
</p>

@anchor LC_GELDKARTE_BLOG_Time
<h3>Time</h3>
<p>
</p>
<p>
Set this property with @ref LC_GeldKarte_BLog_SetTime, 
get it with @ref LC_GeldKarte_BLog_GetTime
</p>

@anchor LC_GELDKARTE_BLOG_KeyId
<h3>KeyId</h3>
<p>
</p>
<p>
Set this property with @ref LC_GeldKarte_BLog_SetKeyId, 
get it with @ref LC_GeldKarte_BLog_GetKeyId
</p>

*/
#include <gwenhywfar/db.h>
#include <gwenhywfar/list2.h>
#include <gwenhywfar/types.h>
#include <gwenhywfar/gwentime.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct LC_GELDKARTE_BLOG LC_GELDKARTE_BLOG;

GWEN_LIST2_FUNCTION_DEFS(LC_GELDKARTE_BLOG, LC_GeldKarte_BLog)

void LC_GeldKarte_BLog_List2_freeAll(LC_GELDKARTE_BLOG_LIST2 *stl);

LC_GELDKARTE_BLOG *LC_GeldKarte_BLog_new();
void LC_GeldKarte_BLog_free(LC_GELDKARTE_BLOG *st);
void LC_GeldKarte_BLog_Attach(LC_GELDKARTE_BLOG *st);
LC_GELDKARTE_BLOG *LC_GeldKarte_BLog_dup(const LC_GELDKARTE_BLOG*st);
LC_GELDKARTE_BLOG *LC_GeldKarte_BLog_fromDb(GWEN_DB_NODE *db);
int LC_GeldKarte_BLog_toDb(const LC_GELDKARTE_BLOG*st, GWEN_DB_NODE *db);
int LC_GeldKarte_BLog_IsModified(const LC_GELDKARTE_BLOG *st);
void LC_GeldKarte_BLog_SetModified(LC_GELDKARTE_BLOG *st, int i);

/**
* Returns the property @ref LC_GELDKARTE_BLOG_Status
*/
int LC_GeldKarte_BLog_GetStatus(const LC_GELDKARTE_BLOG *el);
/**
* Set the property @ref LC_GELDKARTE_BLOG_Status
*/
void LC_GeldKarte_BLog_SetStatus(LC_GELDKARTE_BLOG *el, int d);

/**
* Returns the property @ref LC_GELDKARTE_BLOG_BSeq
*/
int LC_GeldKarte_BLog_GetBSeq(const LC_GELDKARTE_BLOG *el);
/**
* Set the property @ref LC_GELDKARTE_BLOG_BSeq
*/
void LC_GeldKarte_BLog_SetBSeq(LC_GELDKARTE_BLOG *el, int d);

/**
* Returns the property @ref LC_GELDKARTE_BLOG_LSeq
*/
int LC_GeldKarte_BLog_GetLSeq(const LC_GELDKARTE_BLOG *el);
/**
* Set the property @ref LC_GELDKARTE_BLOG_LSeq
*/
void LC_GeldKarte_BLog_SetLSeq(LC_GELDKARTE_BLOG *el, int d);

/**
* Returns the property @ref LC_GELDKARTE_BLOG_Value
*/
int LC_GeldKarte_BLog_GetValue(const LC_GELDKARTE_BLOG *el);
/**
* Set the property @ref LC_GELDKARTE_BLOG_Value
*/
void LC_GeldKarte_BLog_SetValue(LC_GELDKARTE_BLOG *el, int d);

/**
* Returns the property @ref LC_GELDKARTE_BLOG_MerchantId
*/
const char *LC_GeldKarte_BLog_GetMerchantId(const LC_GELDKARTE_BLOG *el);
/**
* Set the property @ref LC_GELDKARTE_BLOG_MerchantId
*/
void LC_GeldKarte_BLog_SetMerchantId(LC_GELDKARTE_BLOG *el, const char *d);

/**
* Returns the property @ref LC_GELDKARTE_BLOG_HSeq
*/
int LC_GeldKarte_BLog_GetHSeq(const LC_GELDKARTE_BLOG *el);
/**
* Set the property @ref LC_GELDKARTE_BLOG_HSeq
*/
void LC_GeldKarte_BLog_SetHSeq(LC_GELDKARTE_BLOG *el, int d);

/**
* Returns the property @ref LC_GELDKARTE_BLOG_SSeq
*/
int LC_GeldKarte_BLog_GetSSeq(const LC_GELDKARTE_BLOG *el);
/**
* Set the property @ref LC_GELDKARTE_BLOG_SSeq
*/
void LC_GeldKarte_BLog_SetSSeq(LC_GELDKARTE_BLOG *el, int d);

/**
* Returns the property @ref LC_GELDKARTE_BLOG_Loaded
*/
int LC_GeldKarte_BLog_GetLoaded(const LC_GELDKARTE_BLOG *el);
/**
* Set the property @ref LC_GELDKARTE_BLOG_Loaded
*/
void LC_GeldKarte_BLog_SetLoaded(LC_GELDKARTE_BLOG *el, int d);

/**
* Returns the property @ref LC_GELDKARTE_BLOG_Time
*/
const GWEN_TIME *LC_GeldKarte_BLog_GetTime(const LC_GELDKARTE_BLOG *el);
/**
* Set the property @ref LC_GELDKARTE_BLOG_Time
*/
void LC_GeldKarte_BLog_SetTime(LC_GELDKARTE_BLOG *el, const GWEN_TIME *d);

/**
* Returns the property @ref LC_GELDKARTE_BLOG_KeyId
*/
int LC_GeldKarte_BLog_GetKeyId(const LC_GELDKARTE_BLOG *el);
/**
* Set the property @ref LC_GELDKARTE_BLOG_KeyId
*/
void LC_GeldKarte_BLog_SetKeyId(LC_GELDKARTE_BLOG *el, int d);


#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* GELDKARTE_BLOG_H */
