/* This file is auto-generated from "lockrequest.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef LOCKREQUEST_P_H
#define LOCKREQUEST_P_H

#include "lockrequest_l.h"


struct LCS_LOCKREQUEST {
  GWEN_LIST_ELEMENT(LCS_LOCKREQUEST)
  int _usage;
  int _modified;

  uint32_t requestId;
  uint32_t clientId;
  GWEN_TIME *lockTime;
  int duration;
  GWEN_TIME *lockUntil;
};








#endif /* LOCKREQUEST_P_H */
