/* This file is auto-generated from "cmdrequest.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef CMDREQUEST_L_H
#define CMDREQUEST_L_H

/** @page P_LCCMD_CMDREQUEST_LIB LCCMD_CmdRequest (lib)
This page describes the properties of LCCMD_CMDREQUEST
*/
#ifdef __cplusplus
extern "C" {
#endif

typedef struct LCCMD_CMDREQUEST LCCMD_CMDREQUEST;

#ifdef __cplusplus
} /* __cplusplus */
#endif

#include <gwenhywfar/misc.h>
#include <gwenhywfar/misc.h>
#include <gwenhywfar/db.h>
#include <gwenhywfar/types.h>
#include <gwenhywfar/gwentime.h>
#include <gwenhywfar/xml.h>

#ifdef __cplusplus
extern "C" {
#endif


GWEN_LIST_FUNCTION_DEFS(LCCMD_CMDREQUEST, LCCMD_CmdRequest)
LCCMD_CMDREQUEST_LIST *LCCMD_CmdRequest_List_dup(const LCCMD_CMDREQUEST_LIST *stl);
LCCMD_CMDREQUEST *LCCMD_CmdRequest_new();
void LCCMD_CmdRequest_free(LCCMD_CMDREQUEST *st);
void LCCMD_CmdRequest_Attach(LCCMD_CMDREQUEST *st);
LCCMD_CMDREQUEST *LCCMD_CmdRequest_dup(const LCCMD_CMDREQUEST*st);LCCMD_CMDREQUEST *LCCMD_CmdRequest_fromDb(GWEN_DB_NODE *db);int LCCMD_CmdRequest_toDb(const LCCMD_CMDREQUEST*st, GWEN_DB_NODE *db);int LCCMD_CmdRequest_IsModified(const LCCMD_CMDREQUEST *st);
void LCCMD_CmdRequest_SetModified(LCCMD_CMDREQUEST *st, int i);

/**
* Returns the property @ref LCCMD_CMDREQUEST_RequestId
*/
GWEN_TYPE_UINT32 LCCMD_CmdRequest_GetRequestId(const LCCMD_CMDREQUEST *el);
/**
* Set the property @ref LCCMD_CMDREQUEST_RequestId
*/
void LCCMD_CmdRequest_SetRequestId(LCCMD_CMDREQUEST *el, GWEN_TYPE_UINT32 d);

/**
* Returns the property @ref LCCMD_CMDREQUEST_RequestTime
*/
const GWEN_TIME *LCCMD_CmdRequest_GetRequestTime(const LCCMD_CMDREQUEST *el);
/**
* Set the property @ref LCCMD_CMDREQUEST_RequestTime
*/
void LCCMD_CmdRequest_SetRequestTime(LCCMD_CMDREQUEST *el, const GWEN_TIME *d);

/**
* Returns the property @ref LCCMD_CMDREQUEST_CmdNode
*/
GWEN_XMLNODE *LCCMD_CmdRequest_GetCmdNode(const LCCMD_CMDREQUEST *el);
/**
* Set the property @ref LCCMD_CMDREQUEST_CmdNode
*/
void LCCMD_CmdRequest_SetCmdNode(LCCMD_CMDREQUEST *el, GWEN_XMLNODE *d);


#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* CMDREQUEST_L_H */
