/* This file is auto-generated from "cmdrequest.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef CMDREQUEST_P_H
#define CMDREQUEST_P_H

#include "cmdrequest_l.h"


struct LCCMD_CMDREQUEST {
  GWEN_LIST_ELEMENT(LCCMD_CMDREQUEST)
  int _usage;
  int _modified;

  GWEN_TYPE_UINT32 requestId;
  GWEN_TIME *requestTime;
  GWEN_XMLNODE *cmdNode;
};






#endif /* CMDREQUEST_P_H */
