/* This file is auto-generated from "cmdrequest.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include "cmdrequest_p.h"
#include <gwenhywfar/misc.h>
#include <gwenhywfar/db.h>
#include <gwenhywfar/debug.h>
#include <assert.h>
#include <stdlib.h>
#include <strings.h>


GWEN_LIST_FUNCTIONS(LCCMD_CMDREQUEST, LCCMD_CmdRequest)


LCCMD_CMDREQUEST *LCCMD_CmdRequest_new() {
  LCCMD_CMDREQUEST *st;

  GWEN_NEW_OBJECT(LCCMD_CMDREQUEST, st)
  st->_usage=1;
  GWEN_LIST_INIT(LCCMD_CMDREQUEST, st)
  return st;
}


void LCCMD_CmdRequest_free(LCCMD_CMDREQUEST *st) {
  if (st) {
    assert(st->_usage);
    if (--(st->_usage)==0) {
  GWEN_LIST_FINI(LCCMD_CMDREQUEST, st)
  GWEN_FREE_OBJECT(st);
    }
  }

}


LCCMD_CMDREQUEST *LCCMD_CmdRequest_dup(const LCCMD_CMDREQUEST *d) {
  LCCMD_CMDREQUEST *st;

  assert(d);
  st=LCCMD_CmdRequest_new();
  st->requestId=d->requestId;
  if (d->requestTime)
    st->requestTime=GWEN_Time_dup(d->requestTime);
  if (d->cmdNode)
    st->cmdNode=d->cmdNode
;  return st;
}


int LCCMD_CmdRequest_toDb(const LCCMD_CMDREQUEST *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "requestId", st->requestId))
    return -1;
  if (st->requestTime)
    if (GWEN_Time_toDb(st->requestTime, GWEN_DB_GetGroup(db, GWEN_DB_FLAGS_DEFAULT, "requestTime")))
      return -1;
  return 0;
}


LCCMD_CMDREQUEST *LCCMD_CmdRequest_fromDb(GWEN_DB_NODE *db) {
LCCMD_CMDREQUEST *st;

  assert(db);
  st=LCCMD_CmdRequest_new();
  LCCMD_CmdRequest_SetRequestId(st, GWEN_DB_GetIntValue(db, "requestId", 0, 0));
  if (1) {
    GWEN_DB_NODE *dbT;

    dbT=GWEN_DB_GetGroup(db, GWEN_PATH_FLAGS_NAMEMUSTEXIST, "requestTime");
    if (dbT) st->requestTime=GWEN_Time_fromDb(dbT);
  }
  st->_modified=0;
  return st;
}


GWEN_TYPE_UINT32 LCCMD_CmdRequest_GetRequestId(const LCCMD_CMDREQUEST *st) {
  assert(st);
  return st->requestId;
}


void LCCMD_CmdRequest_SetRequestId(LCCMD_CMDREQUEST *st, GWEN_TYPE_UINT32 d) {
  assert(st);
  st->requestId=d;
  st->_modified=1;
}




const GWEN_TIME *LCCMD_CmdRequest_GetRequestTime(const LCCMD_CMDREQUEST *st) {
  assert(st);
  return st->requestTime;
}


void LCCMD_CmdRequest_SetRequestTime(LCCMD_CMDREQUEST *st, const GWEN_TIME *d) {
  assert(st);
  if (d)
    st->requestTime=GWEN_Time_dup(d);
  else
    st->requestTime=0;
  st->_modified=1;
}




GWEN_XMLNODE *LCCMD_CmdRequest_GetCmdNode(const LCCMD_CMDREQUEST *st) {
  assert(st);
  return st->cmdNode;
}


void LCCMD_CmdRequest_SetCmdNode(LCCMD_CMDREQUEST *st, GWEN_XMLNODE *d) {
  assert(st);
  if (d)
    st->cmdNode=d;
  else
    st->cmdNode=0;
  st->_modified=1;
}




int LCCMD_CmdRequest_IsModified(const LCCMD_CMDREQUEST *st) {
  assert(st);
  return st->_modified;
}


void LCCMD_CmdRequest_SetModified(LCCMD_CMDREQUEST *st, int i) {
  assert(st);
  st->_modified=i;
}


void LCCMD_CmdRequest_Attach(LCCMD_CMDREQUEST *st) {
  assert(st);
  st->_usage++;
}
LCCMD_CMDREQUEST_LIST *LCCMD_CmdRequest_List_dup(const LCCMD_CMDREQUEST_LIST *stl) {
  if (stl) {
    LCCMD_CMDREQUEST_LIST *nl;
    LCCMD_CMDREQUEST *e;

    nl=LCCMD_CmdRequest_List_new();
    e=LCCMD_CmdRequest_List_First(stl);
    while(e) {
      LCCMD_CMDREQUEST *ne;

      ne=LCCMD_CmdRequest_dup(e);
      assert(ne);
      LCCMD_CmdRequest_List_Add(ne, nl);
      e=LCCMD_CmdRequest_List_Next(e);
    } /* while (e) */
    return nl;
  }
  else
    return 0;
}



