/* This file is auto-generated from "lockrequest.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef LOCKREQUEST_P_H
#define LOCKREQUEST_P_H

#include "lockrequest_l.h"

struct LCCM_LOCKREQUEST {
  GWEN_LIST_ELEMENT(LCCM_LOCKREQUEST)
  int _usage;
  int _modified;

  GWEN_TYPE_UINT32 requestId;
  GWEN_TYPE_UINT32 clientId;
  GWEN_TIME *lockTime;
  int duration;
  GWEN_TIME *lockUntil;
};








#endif /* LOCKREQUEST_P_H */
