/* This file is auto-generated from "lockrequest.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include "lockrequest_p.h"
#include <gwenhywfar/misc.h>
#include <gwenhywfar/db.h>
#include <gwenhywfar/debug.h>
#include <assert.h>
#include <stdlib.h>
#include <strings.h>


GWEN_LIST_FUNCTIONS(LCCM_LOCKREQUEST, LCCM_LockRequest)


LCCM_LOCKREQUEST *LCCM_LockRequest_new() {
  LCCM_LOCKREQUEST *st;

  GWEN_NEW_OBJECT(LCCM_LOCKREQUEST, st)
  st->_usage=1;
  GWEN_LIST_INIT(LCCM_LOCKREQUEST, st)
  return st;
}


void LCCM_LockRequest_free(LCCM_LOCKREQUEST *st) {
  if (st) {
    assert(st->_usage);
    if (--(st->_usage)==0) {
  if (st->lockTime)
    GWEN_Time_free(st->lockTime);
  if (st->lockUntil)
    GWEN_Time_free(st->lockUntil);
  GWEN_LIST_FINI(LCCM_LOCKREQUEST, st)
  GWEN_FREE_OBJECT(st);
    }
  }

}


LCCM_LOCKREQUEST *LCCM_LockRequest_dup(const LCCM_LOCKREQUEST *d) {
  LCCM_LOCKREQUEST *st;

  assert(d);
  st=LCCM_LockRequest_new();
  st->requestId=d->requestId;
  st->clientId=d->clientId;
  if (d->lockTime)
    st->lockTime=GWEN_Time_dup(d->lockTime);
  st->duration=d->duration;
  if (d->lockUntil)
    st->lockUntil=GWEN_Time_dup(d->lockUntil);
  return st;
}


int LCCM_LockRequest_toDb(const LCCM_LOCKREQUEST *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "requestId", st->requestId))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "clientId", st->clientId))
    return -1;
  if (st->lockTime)
    if (GWEN_Time_toDb(st->lockTime, GWEN_DB_GetGroup(db, GWEN_DB_FLAGS_DEFAULT, "lockTime")))
      return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "duration", st->duration))
    return -1;
  if (st->lockUntil)
    if (GWEN_Time_toDb(st->lockUntil, GWEN_DB_GetGroup(db, GWEN_DB_FLAGS_DEFAULT, "lockUntil")))
      return -1;
  return 0;
}


LCCM_LOCKREQUEST *LCCM_LockRequest_fromDb(GWEN_DB_NODE *db) {
LCCM_LOCKREQUEST *st;

  assert(db);
  st=LCCM_LockRequest_new();
  LCCM_LockRequest_SetRequestId(st, GWEN_DB_GetIntValue(db, "requestId", 0, 0));
  LCCM_LockRequest_SetClientId(st, GWEN_DB_GetIntValue(db, "clientId", 0, 0));
  if (1) {
    GWEN_DB_NODE *dbT;

    dbT=GWEN_DB_GetGroup(db, GWEN_PATH_FLAGS_NAMEMUSTEXIST, "lockTime");
    if (dbT) st->lockTime=GWEN_Time_fromDb(dbT);
  }
  LCCM_LockRequest_SetDuration(st, GWEN_DB_GetIntValue(db, "duration", 0, 0));
  if (1) {
    GWEN_DB_NODE *dbT;

    dbT=GWEN_DB_GetGroup(db, GWEN_PATH_FLAGS_NAMEMUSTEXIST, "lockUntil");
    if (dbT) st->lockUntil=GWEN_Time_fromDb(dbT);
  }
  st->_modified=0;
  return st;
}


GWEN_TYPE_UINT32 LCCM_LockRequest_GetRequestId(const LCCM_LOCKREQUEST *st) {
  assert(st);
  return st->requestId;
}


void LCCM_LockRequest_SetRequestId(LCCM_LOCKREQUEST *st, GWEN_TYPE_UINT32 d) {
  assert(st);
  st->requestId=d;
  st->_modified=1;
}


GWEN_TYPE_UINT32 LCCM_LockRequest_GetClientId(const LCCM_LOCKREQUEST *st) {
  assert(st);
  return st->clientId;
}


void LCCM_LockRequest_SetClientId(LCCM_LOCKREQUEST *st, GWEN_TYPE_UINT32 d) {
  assert(st);
  st->clientId=d;
  st->_modified=1;
}


const GWEN_TIME *LCCM_LockRequest_GetLockTime(const LCCM_LOCKREQUEST *st) {
  assert(st);
  return st->lockTime;
}


void LCCM_LockRequest_SetLockTime(LCCM_LOCKREQUEST *st, const GWEN_TIME *d) {
  assert(st);
  if (st->lockTime)
    GWEN_Time_free(st->lockTime);
  if (d)
    st->lockTime=GWEN_Time_dup(d);
  else
    st->lockTime=0;
  st->_modified=1;
}


int LCCM_LockRequest_GetDuration(const LCCM_LOCKREQUEST *st) {
  assert(st);
  return st->duration;
}


void LCCM_LockRequest_SetDuration(LCCM_LOCKREQUEST *st, int d) {
  assert(st);
  st->duration=d;
  st->_modified=1;
}


const GWEN_TIME *LCCM_LockRequest_GetLockUntil(const LCCM_LOCKREQUEST *st) {
  assert(st);
  return st->lockUntil;
}


void LCCM_LockRequest_SetLockUntil(LCCM_LOCKREQUEST *st, const GWEN_TIME *d) {
  assert(st);
  if (st->lockUntil)
    GWEN_Time_free(st->lockUntil);
  if (d)
    st->lockUntil=GWEN_Time_dup(d);
  else
    st->lockUntil=0;
  st->_modified=1;
}


int LCCM_LockRequest_IsModified(const LCCM_LOCKREQUEST *st) {
  assert(st);
  return st->_modified;
}


void LCCM_LockRequest_SetModified(LCCM_LOCKREQUEST *st, int i) {
  assert(st);
  st->_modified=i;
}


void LCCM_LockRequest_Attach(LCCM_LOCKREQUEST *st) {
  assert(st);
  st->_usage++;
}
LCCM_LOCKREQUEST_LIST *LCCM_LockRequest_List_dup(const LCCM_LOCKREQUEST_LIST *stl) {
  if (stl) {
    LCCM_LOCKREQUEST_LIST *nl;
    LCCM_LOCKREQUEST *e;

    nl=LCCM_LockRequest_List_new();
    e=LCCM_LockRequest_List_First(stl);
    while(e) {
      LCCM_LOCKREQUEST *ne;

      ne=LCCM_LockRequest_dup(e);
      assert(ne);
      LCCM_LockRequest_List_Add(ne, nl);
      e=LCCM_LockRequest_List_Next(e);
    } /* while (e) */
    return nl;
  }
  else
    return 0;
}



